services:
  backend-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: wener_rs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - backend-db-vol:/data/postgres

  backend:
    build:
      target: development
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./static:/app/static
      - ./upload:/app/upload
      - ./proto:/proto
    depends_on:
      - backend-db
    command: ["cargo", "watch", "-x", "run"]

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
    command: ["trunk", "serve"]

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    depends_on:
      - backend-db

  backend-redis:
    image: redis:7.4.0-alpine3.20
    volumes:
      - backend-redis-vol:/data
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:2.54.0
    environment:
      RI_PROXY_PATH: /redisinsight
    volumes:
      - redisinsight-vol:/data

  nginx:
    image: nginx:stable-alpine3.17
    ports:
      - "3000:80"
    volumes:
      - ./nginx/development:/etc/nginx/conf.d
      - ./static:/www/static
    depends_on:
      - backend
      - pgadmin

volumes:
  backend-db-vol:
  backend-redis-vol:
  redisinsight-vol:
  pgadmin-vol:
